[package]
name = "rusty_browser"
version = "2.1.0"
edition = "2021"

[dependencies]
gtk = { package = "gtk4", version = "0.6" }
webkit6 = "0.1"
glib = "0.17"
bytes = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"